name: Continuous Integration # 这是工作流程的名称

on: [push, pull_request] # 定义触发工作流程的事件

jobs:
  build:
    runs-on: ubuntu-latest # 定义运行工作流程的虚拟环境

    steps:
      - uses: actions/checkout@v2 # 检出代码

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: 'JigglypuffStitch/ruanjian'
